apiVersion: apps/v1
kind: Deployment
metadata:
  name: cont-postgres
  namespace: cont
  labels:
    app: cont-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cont-postgres
  template:
    metadata:
      labels:
        app: cont-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: cont
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cont-secrets
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}